### PR TITLE
Fix keychain key bug

### LINKED ISSUE #236: KeychainAttribute does not work as expected
**Describe the bug**

Specifying `.useDataProtectionKeychain` and/or `.keychainAccessGroup("<group>")` when creating a `KeychainStore` has no effect on the keychain item.

**To Reproduce**

1. Allocate a store:
    ```swift
    let store = KeychainStore(
        itemName: "foo",
        keychainAttributes: [.useDataProtectionKeychain, .keychainAccessGroup(name: "TEAMID.com.example.foobar")]
    )
    ```
2. Save an `AuthSession`
    ```swift
    try store.save(authSession: auth)
    ```
3. Check the 'Access Control' tab in Keychain Access. There's only an entry for the calling application under 'Always allow access by these applications'.

**Expected behavior**

- Specifying `.useDataProtectionKeychain` saves the item in the 'Local Items' keychain
- Specifying `.keychainAccessGroup` allows members of that group access to the item

**Environment**

- OS: macOS 13.6.3 (22G436)
- Library: `41aba100f28395ebe842cd66e5d371cdd46c6792`

**Additional context**

I believe there's a bug in [`KeychainAttribute.keyName`](https://github.com/google/GTMAppAuth/blob/master/GTMAppAuth/Sources/KeychainStore/KeychainAttribute.swift#L32). It should not return the quoted constants but rather the constants itself. So `kSecUseDataProtectionKeychain` instead of `"kSecUseDataProtectionKeychain"` because `KeychainWrapper` uses the return value as-is to assemble the query dictionary for `SecItem(Add|Delete|CopyMatching)` [here](https://github.com/google/GTMAppAuth/blob/master/GTMAppAuth/Sources/KeychainStore/KeychainHelper.swift#L59)

### PR DESCRIPTION
**Pull request by mdmathias**
This PR addresses [a bug](#236) where the key attributes used to query the keychain were not being added correctly, and where therefore unused. The mistake was that the key names were assumed to match the static constants.

Fixes #236.

### CODE REVIEW

**Comment by mdmathias** [comment]
Hi @olvrlrnz please take a look and help us to make sure that this change meets the need. Thanks!

File: Examples/Example-macOS/Source/GTMAppAuthExampleViewController.m [hunk 1]
```diff
@@ -30,6 +30,8 @@
 
 #import "AppDelegate.h"
 
+static NSString *const kTeamIDPrefix = @"YOUR_TEAM_ID";
```
Comment (yalkhder) [inline Examples/Example-macOS/Source/GTMAppAuthExampleViewController.m:33]: nit: Add brief?

File: Examples/Example-macOS/Source/GTMAppAuthExampleViewController.m [hunk 2]
```diff
@@ -65,9 +67,18 @@ @implementation GTMAppAuthExampleViewController
 - (void)viewDidLoad {
   [super viewDidLoad];
 
-  self.keychainStore = [[GTMKeychainStore alloc] initWithItemName:kExampleAuthorizerKey];
+  GTMKeychainAttribute *dataProtection = [GTMKeychainAttribute useDataProtectionKeychain];
+  NSString *bundleID = @"com.example.GTMAppAuth.Example-macOS.test-group";
```
Comment (yalkhder) [inline Examples/Example-macOS/Source/GTMAppAuthExampleViewController.m:71]: Can we grab the bundleID from [`bundleIdentifier`](https://developer.apple.com/documentation/foundation/nsbundle/1418023-bundleidentifier)? Or put it up as a `static const`?

**Review by yalkhder — CHANGES_REQUESTED** [review]

**Comment by olvrlrnz** [comment]
Just tried it in our code base, LGTM
image

**Review by yalkhder — APPROVED** [review]

**Comment by mdmathias** [comment]
@olvrlrnz Sorry for bugging you again, but I made some changes since you last looked. Would you mind double checking for me? 🙏

File: GTMAppAuth/Sources/KeychainStore/KeychainStore.swift [hunk 3]
```diff
@@ -101,10 +102,20 @@ public final class KeychainStore: NSObject, AuthSessionStore {
   @objc(saveAuthSession:error:)
   public func save(authSession: AuthSession) throws {
     let authSessionData: Data = try authSessionData(fromAuthSession: authSession)
+
+    var maybeAccessibility: CFString? = kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly
+    if #available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *) {
+#if os(macOS)
```
Comment (olvrlrnz) [inline GTMAppAuth/Sources/KeychainStore/KeychainStore.swift:108]: `#if` is a compile-time option, `if #available` is evaluated at runtime. Wouldn't it be better to just have
```swift
if #available(macOS 10.15, *), !keychainAttributes.contains(.useDataProtectionKeychain) {
    // accessibility options on macOS only work when using the data protection keychain
    maybeAccessibility = nil
}
```

File: GTMAppAuth/Sources/KeychainStore/KeychainStore.swift [hunk 4]
```diff
@@ -118,10 +129,20 @@ public final class KeychainStore: NSObject, AuthSessionStore {
   @objc(saveAuthSession:withItemName:error:)
   public func save(authSession: AuthSession, withItemName itemName: String) throws {
     let authSessionData = try authSessionData(fromAuthSession: authSession)
+
+    var maybeAccessibility: CFString? = kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly
+    if #available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *) {
```
Comment (olvrlrnz) [inline GTMAppAuth/Sources/KeychainStore/KeychainStore.swift:134]: `#if` is a compile-time option, `if #available` is evaluated at runtime. Wouldn't it be better to just have
```swift
if #available(macOS 10.15, *), !keychainAttributes.contains(.useDataProtectionKeychain) {
    // accessibility options on macOS only work when using the data protection keychain
    maybeAccessibility = nil
}
```

File: GTMAppAuth/Sources/KeychainStore/KeychainStore.swift [hunk 5]
```diff
@@ -101,10 +102,20 @@ public final class KeychainStore: NSObject, AuthSessionStore {
   @objc(saveAuthSession:error:)
   public func save(authSession: AuthSession) throws {
```
Comment (olvrlrnz) [inline GTMAppAuth/Sources/KeychainStore/KeychainStore.swift:103]: Why not call `self.save(authSession: authSession, withItemName: self.itemName)`? Then you don't have to do the accessibility stuff twice?

File: GTMAppAuth/Sources/KeychainStore/KeychainStore.swift [hunk 6]
```diff
@@ -268,6 +289,18 @@ public final class KeychainStore: NSObject, AuthSessionStore {
         .persistenceResponseString(forAuthSession: authSession) else {
       throw KeychainStore.Error.failedToCreateResponseStringFromAuthSession(authSession)
     }
+
+    if #available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *) {
```
Comment (olvrlrnz) [inline GTMAppAuth/Sources/KeychainStore/KeychainStore.swift:293]: This is also mixing compile-time and runtime checks

File: GTMAppAuth/Sources/KeychainStore/KeychainStore.swift (hunk 4 above)
Comment (mdmathias) [reply GTMAppAuth/Sources/KeychainStore/KeychainStore.swift:134]: I initially wanted to have a check like you have above, but it doesn't work as expected. As you point out, `if #available` is a runtime check, which means running tests on tvOS (for example) will fail due to `.useDataProtectionKeychain` not being available (or not being guaranteed to be available) during compilation.

Since we only want this logic to apply for certain versions of macOS, we need to do something like I have: check that we are running in an OS version where this attribute is available, check if we're on macOS, then check if the supplied attributes contains `.useDataProtectionKeychain`, and update the accessibility attribute accordingly.

Supplying the accessibility option on `KeychainAttribute` is a good idea, but doing so would change the previous/default behavior where we specify `kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly` automatically - it would become an attribute that developers can control (by becoming a case on the `KeychainAttribute.Attribute` enum). 

We can consider something like this in the future, but I'd like to defer that to future consideration.

File: GTMAppAuth/Sources/KeychainStore/KeychainStore.swift (hunk 5 above)
Comment (mdmathias) [reply GTMAppAuth/Sources/KeychainStore/KeychainStore.swift:103]: Good idea. Done. :)

File: GTMAppAuth/Sources/KeychainStore/KeychainStore.swift (hunk 6 above)
Comment (mdmathias) [reply GTMAppAuth/Sources/KeychainStore/KeychainStore.swift:293]: Resolving. Let's consolidate this discussion above.

**Review by olvrlrnz — APPROVED** [review]

**Review by yalkhder — APPROVED** [review]

**Review by olvrlrnz — APPROVED** [review]

**Comment by olvrlrnz** [comment]
Thanks for fixing this. Would it be possible to create a 4.0.1 release so we can update the package in Xcode?

**Comment by mdmathias** [comment]
Absolutely. We need to figure out what version we call this. In any case, we will be making a new release to include a privacy manifest very shortly. I think that will come out in the next few weeks. Stay tuned for that, and sorry for the delay.
